language: rust

rust:
  - nightly
  - stable
 
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo test --verbose --all-features
