[package]
name = "gltfgen"
version = "0.2.1"
authors = ["Egor Larionov <egor.larionov@gmail.com>"]
edition = "2018"

description = "glTF 2.0 scene generator from mesh sequences"
documentation = "https://docs.rs/gltfgen"
repository = "https://github.com/elrnv/gltfgen"
homepage = "https://github.com/elrnv/gltfgen"
readme = "README.md"
license = "MPL-2.0"
keywords = ["glTF", "VTK", "3D", "asset", "generator"]

[dependencies]
#gltf = { git = "https://github.com/elrnv/gltf" }
gltf = { version = "0.14", features = ["extras"] }
structopt = "0.3"
regex = "1"
glob = "0.3"
gut = { version = "0.4", features = ["io"] }
byteorder = "1"
pbr = "1"
rayon = "1"
syn = "1" # For parsing attributes
heck = "0.3" # For converting case
ron = "0.5"
serde = "1.0"

[features]
empty-sparse-base-buffer-view = []
